#!/bin/bash
# =============================================================================
# transfer-disable-source.sh  —  Safely disable the bot on the SOURCE server
# =============================================================================
# Run this ONLY after confirming the destination server is working correctly.
#
# What it does:
#   1. Stops and removes the bot container
#   2. Disables the docker-compose restart policy  (prevents accidental restart)
#   3. Creates a DISABLED sentinel file to block re-launch
#   4. Optionally: removes the Docker volume (DESTRUCTIVE — disabled by default)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] ✔ ${NC}$1"; }
info() { echo -e "${CYAN}[$(date +'%Y-%m-%d %H:%M:%S')] ℹ ${NC}$1"; }
warn() { echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] ⚠ ${NC}$1"; }
err()  { echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ✖ ERROR: ${NC}$1" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo ""
echo -e "${RED}══════════════════════════════════════════════════════${NC}"
echo -e "${RED}  WARNING: This will PERMANENTLY disable the source bot${NC}"
echo -e "${RED}══════════════════════════════════════════════════════${NC}"
echo ""
echo "  Project dir: $PROJECT_DIR"
echo ""
echo "  This action:"
echo "    • Stops and removes the alovpn-bot container"
echo "    • Stops and removes the alovpn-backup container"
echo "    • Disables docker compose auto-restart"
echo "    • Creates DISABLED sentinel file"
echo ""
read -rp "  Are you sure you want to disable this server? (yes/no): " CONFIRM
[[ "$CONFIRM" == "yes" ]] || { echo "Aborted."; exit 0; }

# ── 1. stop and remove containers ─────────────────────────────────────────────
info "Stopping containers…"
cd "$PROJECT_DIR"

docker compose stop  2>/dev/null || true
docker compose down  2>/dev/null || true

log "Containers stopped and removed."

# ── 2. create override to set restart: no on all services ─────────────────────
info "Disabling restart policy via docker-compose.override.yml…"
cat > "$PROJECT_DIR/docker-compose.override.yml" <<'EOF'
# AUTO-GENERATED by transfer-disable-source.sh
# This file overrides the restart policy so the bot does NOT start on reboot.
services:
  bot:
    restart: "no"
  backup:
    restart: "no"
EOF
log "docker-compose.override.yml created."

# ── 3. write sentinel file ────────────────────────────────────────────────────
SENTINEL="$PROJECT_DIR/DISABLED"
cat > "$SENTINEL" <<EOF
This bot instance was DISABLED on $(date -u +%Y-%m-%dT%H:%M:%SZ).
The database and configuration have been transferred to another server.

DO NOT restart this bot. The active instance is on the destination server.

To re-enable (emergency only):
  rm $SENTINEL $PROJECT_DIR/docker-compose.override.yml
  cd $PROJECT_DIR && docker compose up -d
EOF
log "Sentinel file created: $SENTINEL"

# ── 4. optional: delete docker volume ─────────────────────────────────────────
echo ""
warn "The Docker volume 'alovpn-bot_bot_data' still exists on this machine."
warn "If you are 100%% sure the destination is working and you don't need a local copy:"
echo ""
read -rp "  Delete the Docker volume (IRREVERSIBLE)? (yes/no): " DEL_VOL
if [[ "$DEL_VOL" == "yes" ]]; then
    docker volume rm alovpn-bot_bot_data 2>/dev/null && log "Volume deleted." || warn "Volume already gone or in use."
else
    warn "Volume kept. You can delete it later: docker volume rm alovpn-bot_bot_data"
fi

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN} Source server disabled.${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo ""
echo "  Source is now inert. The destination server is the live instance."
echo ""
